// Code generated by Kitex v0.12.2. DO NOT EDIT.

package agentservice

import (
	"context"
	"errors"
	agent "github.com/bitdance-panic/gobuy/app/rpc/kitex_gen/agent"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ask": kitex.NewMethodInfo(
		askHandler,
		newAgentServiceAskArgs,
		newAgentServiceAskResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SendMessage": kitex.NewMethodInfo(
		sendMessageHandler,
		newAgentServiceSendMessageArgs,
		newAgentServiceSendMessageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetHistoryMessages": kitex.NewMethodInfo(
		getHistoryMessagesHandler,
		newAgentServiceGetHistoryMessagesArgs,
		newAgentServiceGetHistoryMessagesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	agentServiceServiceInfo                = NewServiceInfo()
	agentServiceServiceInfoForClient       = NewServiceInfoForClient()
	agentServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return agentServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return agentServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return agentServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AgentService"
	handlerType := (*agent.AgentService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "agent",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.12.2",
		Extra:           extra,
	}
	return svcInfo
}

func askHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*agent.AgentServiceAskArgs)
	realResult := result.(*agent.AgentServiceAskResult)
	success, err := handler.(agent.AgentService).Ask(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAgentServiceAskArgs() interface{} {
	return agent.NewAgentServiceAskArgs()
}

func newAgentServiceAskResult() interface{} {
	return agent.NewAgentServiceAskResult()
}

func sendMessageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*agent.AgentServiceSendMessageArgs)
	realResult := result.(*agent.AgentServiceSendMessageResult)
	success, err := handler.(agent.AgentService).SendMessage(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAgentServiceSendMessageArgs() interface{} {
	return agent.NewAgentServiceSendMessageArgs()
}

func newAgentServiceSendMessageResult() interface{} {
	return agent.NewAgentServiceSendMessageResult()
}

func getHistoryMessagesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*agent.AgentServiceGetHistoryMessagesArgs)
	realResult := result.(*agent.AgentServiceGetHistoryMessagesResult)
	success, err := handler.(agent.AgentService).GetHistoryMessages(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAgentServiceGetHistoryMessagesArgs() interface{} {
	return agent.NewAgentServiceGetHistoryMessagesArgs()
}

func newAgentServiceGetHistoryMessagesResult() interface{} {
	return agent.NewAgentServiceGetHistoryMessagesResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Ask(ctx context.Context, req *agent.AskReq) (r *agent.AskResp, err error) {
	var _args agent.AgentServiceAskArgs
	_args.Req = req
	var _result agent.AgentServiceAskResult
	if err = p.c.Call(ctx, "ask", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SendMessage(ctx context.Context, req *agent.ChatMessageReq) (r *agent.ChatMessageResp, err error) {
	var _args agent.AgentServiceSendMessageArgs
	_args.Req = req
	var _result agent.AgentServiceSendMessageResult
	if err = p.c.Call(ctx, "SendMessage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetHistoryMessages(ctx context.Context, req *agent.HistoryMessageReq) (r *agent.HistoryMessageResp, err error) {
	var _args agent.AgentServiceGetHistoryMessagesArgs
	_args.Req = req
	var _result agent.AgentServiceGetHistoryMessagesResult
	if err = p.c.Call(ctx, "GetHistoryMessages", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
